# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#'Calculates the species on the island initially when \code{nonoceanic_pars[1]
#'!= 0}
#'
#'@param prob_samp probability of a species being sampled
#'from the mainland pool
#'@param prob_nonend probability of a species sampled being non-endemic
#'@param mainland_n number of species in the mainland pool
#'
#'@return A list of non-endemic species, endemic species and the new
#'mainland species pool
#'@noRd
#' @export
DAISIE_nonoceanic_spec_cpp <- function(prob_samp, prob_nonend, mainland_n) {
    .Call(`_DAISIEsims_DAISIE_nonoceanic_spec_cpp`, prob_samp, prob_nonend, mainland_n)
}

#' Calculates the area at a point in time from a beta function
#'
#' @inheritParams default_params_doc
#'
#' @keywords internal
#'
#' @author Joshua Lambert, Pedro Neves, Shu Xie
#'
#' @return Numeric
NULL

#' Function to describe changes in area through time.
#'
#' @inheritParams default_params_doc
#'
#' @keywords internal
#' @family rate calculations
#' @author Pedro Neves, Joshua Lambert
#' @references
#' Valente, Luis M., Rampal S. Etienne, and Albert B. Phillimore.
#' "The effects of island ontogeny on species diversity and phylogeny."
#' Proceedings of the Royal Society of London B: Biological
#' Sciences 281.1784 (2014): 20133227.
NULL

#' Calculate per-capita immigration rate
#'
#' This function is only called directly inside the RHS of the ontogeny
#' likelihood functions. In all other cases \code{\link{get_immig_rate}()} is to
#' be called instead.
#'
#' @inheritParams default_params_doc
#'
#' @return A numeric with the per-capita immigration rate given A(t) and K.
#' @noRd
NULL

#' Calculate immigration rate
#' @description Internal function.
#' Calculates the immigration rate given the current number of
#' species in the system, the carrying capacity
#'
#' @inheritParams default_params_doc
#'
#' @keywords internal
#' @family rate calculations
#' @author Pedro Neves, Joshua Lambert
#' @references Valente, Luis M., Rampal S. Etienne, and Albert B. Phillimore.
#' "The effects of island ontogeny on species diversity and phylogeny."
#' Proceedings of the Royal Society of London B: Biological Sciences 281.1784 (2014): 20133227.
NULL

#' Function to describe per-capita changes in extinction rate through time
#'
#' This function is only called directly inside the RHS of the ontogeny
#' likelihood functions. In all other cases \code{\link{get_ext_rate}()} is to
#' be called instead.
#'
#' @inheritParams default_params_doc
#'
#' @return Numeric with per capita extinction rate, given A(t), x, and mu0.
#' @noRd
NULL

#' Calculate extinction rate
#'
#' @inheritParams default_params_doc
#'
#' @return A numeric, with the extinction rate given the base extinction rate,
#' if present, the hyperparemeter \code{x}, A(t) if time-dependent and traits
#' if running a traint model.
#'
#' @keywords internal
#' @family rate calculations
#' @references Valente, Luis M., Rampal S. Etienne, and Albert B. Phillimore.
#' "The effects of island ontogeny on species diversity and phylogeny."
#' Proceedings of the Royal Society of London B: Biological Sciences 281.1784
#' (2014): 20133227.
#' @author Pedro Neves, Joshua Lambert, Shu Xie
NULL

#' Calculate anagenesis rate
#' @description Internal function.
#' Calculates the anagenesis rate given the current number of
#' immigrant species and the per capita rate.
#'
#' @inheritParams default_params_doc
#'
#' @keywords internal
#' @family rate calculations
#' @author Pedro Neves, Joshua Lambert, Shu Xie
NULL

#' Calculate per-capita cladogenesis rate
#'
#' This function is only called directly inside the RHS of the ontogeny
#' likelihood functions. In all other cases \code{\link{get_clado_rate}()} is to
#' be called instead.
#'
#' @inheritParams default_params_doc
#'
#' @return Numeric with the per-capita cladogenesis rate given a base
#' cladogenesis rate, K, A and the d hyperparameter.
#' @noRd
NULL

#' Calculate cladogenesis rate
#' @description Internal function.
#' Calculates the cladogenesis rate given the current number of
#' species in the system, the carrying capacity and the per capita cladogenesis
#' rate
#'
#' @inheritParams default_params_doc
#'
#' @keywords internal
#' @author Pedro Neves, Joshua Lambert, Shu Xie
NULL

#' Calculates algorithm rates
#' @description Internal function that updates the all the rates and
#' max extinction horizon at time t.
#' @family rate calculations
#'
#' @inheritParams default_params_doc
#'
#' @seealso \code{\link{update_max_rates}()}
#' @keywords internal
#' @return a named list with the updated effective rates.
#' @export
update_rates_cpp <- function(timeval, total_time, gam, laa, lac, mu, hyper_pars, area_pars, K, num_spec, num_immigrants, mainland_n, peak = 0L, island_ontogeny = 0L, sea_level = 0L) {
    .Call(`_DAISIEsims_update_rates_cpp`, timeval, total_time, gam, laa, lac, mu, hyper_pars, area_pars, K, num_spec, num_immigrants, mainland_n, peak, island_ontogeny, sea_level)
}

#' Samples what event to happen next
#'
#' @inheritParams default_params_doc
#'
#'@return numeric indicating what event will happen, or a supposed event that
#' would happen in some timesteps of the ontogeny algorithm.
#' \itemize{
#'   \item{[1]: immigration event}
#'   \item{[2]: extinction event}
#'   \item{[3]: cladogenesis event}
#'   \item{[4]: anagenesis event}
#' }
#' @keywords internal
#' @author Pedro Neves
#' @export
DAISIE_sample_event_cr_cpp <- function(immig_rate, ext_rate, ana_rate, clado_rate) {
    .Call(`_DAISIEsims_DAISIE_sample_event_cr_cpp`, immig_rate, ext_rate, ana_rate, clado_rate)
}

#' Updates state of island given sampled event for a constant rate case.
#'
#' Makes the event happen by updating island species matrix and species IDs.
#' What event happens is determined by the sampling in the algorithm.
#'
#' @inheritParams default_params_doc
#'
#' @return The updated state of the system, which is a list with the
#' \code{island_spec} matrix, an integer \code{maxspecID} with the most recent
#' ID of species and the \code{stt_table}, a matrix with the current species
#' through time table.
#'
#' @keywords internal
#'
#' @seealso \link{DAISIE_sim_core_cr},
#' \link{DAISIE_sim_update_state_cr}
#' @export
DAISIE_sim_update_state_cr_cpp <- function(timeval, total_time, possible_event, maxspecID, mainland_spec, stt_table_r, island_spec_r) {
    .Call(`_DAISIEsims_DAISIE_sim_update_state_cr_cpp`, timeval, total_time, possible_event, maxspecID, mainland_spec, stt_table_r, island_spec_r)
}

#' Update internal Gillespie bookeeping objects
#'
#' @param stt_table A species=through-time table.
#' @param total_time Simulated amount of time.
#' @param timeval Current time of simulation.
#' @param mainland_spec A vector with the numeric IDs of the mainland species
#' (i.e. potential colonizers).
#' @param island_spec A matrix with the species on the island (state of the
#' system at each time point).
#'
#' @return A named list with the updated input arguments at time of simulation.
#'
#' @noRd
#' @export
DAISIE_spec_tables_cpp <- function(total_time, timeval, init_nonend_spec, init_end_spec, mainland_spec, init_nonend_spec_vec, init_end_spec_vec, maxspecID) {
    .Call(`_DAISIEsims_DAISIE_spec_tables_cpp`, total_time, timeval, init_nonend_spec, init_end_spec, mainland_spec, init_nonend_spec_vec, init_end_spec_vec, maxspecID)
}

